#!/bin/sh
#
# Check plugin to collect performance data of local interfaces on Linux hosts
# get current version: https://github.com/widhalmt/check_local_interfaces
#
# made by Thomas Widhalm <thomas.widhalm@netways.de>
# made for Netways GmbH http://www.netways.de
# version 0.1
# 2017/02/08
#
# most of the code taken from "dnsmichi" : https://github.com/Icinga/wiki-archive/blob/master/service-monitoring/01_12_01_check_interface.md

IFCONFIG="/sbin/ifconfig"

if [ $# -ne 1 -o "$1" = "" -o "$1" = "-h" ]; then
   echo "Usage: `basename $0` InterfaceName"
   echo "Outputs the traffic and error data from an 'ifconfig InterfaceName'"
   exit 3
else
   IFACE=$1
fi

if [ "${IFACE}" == "all" ]
then
  echo "Check all interfaces"
  IFACE=$(${IFCONFIG} | grep -v ^[[:space:]] | grep -v ^$ | grep -v ^lo | awk '{print $1}' | tr -d :)
fi

for i in ${IFACE}
do
  DATA="$($IFCONFIG $i 2>/dev/null | grep '^ *[TR]X packet' | \
  awk '{ for (i=1;i<NF;i++) printf " %s_%s",$1,$i; }' | \
  sed -e 's/s /s:/g' -e 's/([0-9.]*//g' -e 's/:[TR]X_/:/g' -e 's/TX_TX//g' -e 's/TX_$//g' -e 's/;/ /g' -e 's/\([A-Za-z0-9_]*\):\([0-9][0-9]*\)/ \1=\2; /g' -e 's/ [^; ][^; ]* //g' -e 's/; */ /g' -e "s/ RX/ ${i}_RX/g" -e "s/ TX/ ${i}_TX/g")"
  if [ "$DATA" != "" ]; then
    OUTPUT="$OUTPUT $DATA"
  else
     echo "UNKNOWN: Cannot read counters of interface $i"
     exit 3
  fi
done
  OUTPUT="OK: Data read|${OUTPUT}"
  echo ${OUTPUT}
  exit 0
fi

